changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"
  - packages/docsite/**
  - packages/test-suite-*/**

compressionLevel: mixed

enableGlobalCache: false

enableInlineHunks: true

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@testing-library/react@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  gatsby@*:
    dependencies:
      babel-plugin-styled-components: ^1.11.1
  react-frame-component@*:
    peerDependenciesMeta:
      react-dom:
        optional: true

yarnPath: .yarn/releases/yarn-4.9.3.cjs
